# Python后端最小化部署配置示例
# dev分支和main分支推送时自动选择环境配置文件执行

name: Python后端部署

on:
  push:
    branches:
      - main
      - develop
      - dev

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: 部署生产环境
    uses: ./.github/workflows/sub-deploy.yml
    with:
      environment: 生产
      image_name: python-backend

  deploy-test:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/develop'
    name: 部署测试环境
    uses: ./.github/workflows/sub-deploy.yml
    with:
      environment: 测试
      image_name: python-backend